version: '3'

services:
  django-site:
    build:
      context: ./django_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./django_service:/djansite
    command: [/djansite/docker/django.sh]
      # sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - karma

  fastapi-site:
    build:
      context: ./fastapi_service
    env_file:
      - .env
    ports:
      - "8050:8050"
    volumes:
      - ./fastapi_service:/fassite
    command: [/fassite/docker/fastapi.sh]

    depends_on:
      - karma

  karma:
    container_name: karma
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
